2024-10-04 20:51:18,721 mloop                INFO     M-LOOP version 3.3.4
2024-10-04 20:51:18,721 mloop                DEBUG    M-LOOP Logger configured.
2024-10-04 20:51:18,721 mloop.interfaces     DEBUG    Creating interface.
2024-10-04 20:51:18,758 mloop.controllers    DEBUG    Controller init completed.
2024-10-04 20:51:18,759 mloop.learners.1     DEBUG    Learner init completed.
2024-10-04 20:51:18,761 mloop.learners.2     DEBUG    Learner init completed.
2024-10-04 20:51:18,761 mloop.controllers    INFO     Optimization started.
2024-10-04 20:51:18,764 mloop.interfaces     DEBUG    Entering main loop of interface.
2024-10-04 20:51:18,765 mloop.controllers    DEBUG    ML learner started.
2024-10-04 20:51:18,779 mloop.controllers    DEBUG    Starting training optimization.
2024-10-04 20:51:18,780 mloop.controllers    INFO     Run: 0 (training)
2024-10-04 20:51:18,786 mloop.controllers    INFO     params [160.01279901   1.80732452]
2024-10-04 20:51:46,347 mloop.interfaces     DEBUG    Interface ended
2024-10-04 20:51:46,923 mloop.controllers    ERROR    The interface raised an error with traceback:
  File "/Users/michaelmitchell/Library/Caches/pypoetry/virtualenvs/qlics-GZr2JkFu-py3.9/lib/python3.9/site-packages/mloop/interfaces.py", line 133, in run
    cost_dict = self.get_next_cost_dict(params_dict)

  File "/Users/michaelmitchell/qlicS/src/qlicS/mloop_controller.py", line 65, in get_next_cost_dict
    return self.get_run_info(self.experiment_dir, params)

  File "/Users/michaelmitchell/qlicS/opt_examples/pruneing/mloop_formulae.py", line 24, in get_run_info
    if scat := run_from_file(

  File "/Users/michaelmitchell/qlicS/src/qlicS/console_resources.py", line 418, in run_from_file
    return exp_sequence_controller.create_and_run_sim_gen()

  File "/Users/michaelmitchell/qlicS/src/qlicS/exp_sequence_controller.py", line 57, in create_and_run_sim_gen
    scat = get_scattering()

  File "/Users/michaelmitchell/qlicS/src/qlicS/scattering.py", line 75, in get_scattering
    start_stop_f_set + [illuminate(start_stop_f_set, laser_config)]

  File "/Users/michaelmitchell/qlicS/src/qlicS/scattering.py", line 46, in illuminate
    vels = velocities()

  File "/Users/michaelmitchell/qlicS/src/qlicS/analysis.py", line 37, in velocities
    _, data = pl_func.readdump_inhomogenous(f"{dump_dir}positions.txt")

  File "/Users/michaelmitchell/qlicS/src/qlicS/pylion/functions.py", line 565, in readdump_inhomogenous
    sorted_block = [[None] * (len(unsorted_block[0]) - 1) for _ in range(max_atoms)]

  File "/Users/michaelmitchell/qlicS/src/qlicS/pylion/functions.py", line 565, in <listcomp>
    sorted_block = [[None] * (len(unsorted_block[0]) - 1) for _ in range(max_atoms)]

2024-10-04 20:51:46,923 mloop.controllers    WARNING  Controller ended due to exception of some kind. Starting shut down...
2024-10-04 20:51:46,924 mloop.controllers    DEBUG    ML learner end set.
2024-10-04 20:51:47,659 mloop.controllers    DEBUG    ML learner joined
2024-10-04 20:51:47,659 mloop.controllers    INFO     Machine learning learner did not provide best and/or all minima.
2024-10-04 20:51:47,659 mloop.controllers    DEBUG    Learner end event set.
2024-10-04 20:51:47,659 mloop.controllers    DEBUG    Interface end event set.
2024-10-04 20:51:47,890 mloop.learners.1     DEBUG    Learner end signal received. Ending
2024-10-04 20:51:48,892 mloop.controllers    DEBUG    Learner joined.
2024-10-04 20:51:48,892 mloop.controllers    DEBUG    Interface joined.
2024-10-04 20:51:48,895 mloop.controllers    WARNING  Safely shut down. Below are results found before exception.
2024-10-04 20:51:48,896 mloop.controllers    INFO     Optimization ended because:
2024-10-04 20:51:48,896 mloop.controllers    INFO     	* Error occurred.
2024-10-04 20:51:48,896 mloop.controllers    INFO     Results:
2024-10-04 20:51:48,896 mloop.controllers    INFO     	* Best parameters found: nan
2024-10-04 20:51:48,896 mloop.controllers    INFO     	* Best cost returned: inf +/- nan
2024-10-04 20:51:48,896 mloop.controllers    INFO     	* Best run index: nan
